CREATE SCHEMA IF NOT EXISTS b2b_enron;

CREATE TABLE IF NOT EXISTS b2b_enron.enron_emails (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    message_id VARCHAR UNIQUE NOT NULL,
    sender VARCHAR NOT NULL,
    recipients VARCHAR[] NOT NULL,
    subject VARCHAR,
    body TEXT,
    date TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
