-- Grant usage on schemas
GRANT USAGE ON SCHEMA public TO sso_app;
GRANT USAGE ON SCHEMA platform TO sso_app;
GRANT USAGE ON SCHEMA b2b TO sso_app;
GRANT USAGE ON SCHEMA b2c TO sso_app;
GRANT USAGE ON SCHEMA domain TO sso_app;

-- Grant access to all tables in schemas
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO sso_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA platform TO sso_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA b2b TO sso_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA b2c TO sso_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA domain TO sso_app;

-- Grant access to all sequences (for auto-increment IDs)
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO sso_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA platform TO sso_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA b2b TO sso_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA b2c TO sso_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA domain TO sso_app;

-- Ensure future tables also get these permissions (optional but good practice)
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO sso_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA platform GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO sso_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA b2b GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO sso_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA b2c GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO sso_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA domain GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO sso_app;
